LibreELEC support
LS80/script.openelec.devupdate pull request #29
Opened 2016-04-18 15:15 UTC by neox387

This will add LibreELEC support,

However official releases do not work, this is also broken for me on your build for openelec, and getting a datetime error from beautifulsoup4 at line 118:

` return dict((unicode(iter_contents.next().string), tag['datetime'])
                    for tag in iter_contents`

2016-05-22 05:17 UTC, LS80 commented
Thanks, I will review this.

2016-12-04 19:37 UTC, LS80 requested changes
Thanks for the PR. I've requested a few changes. Once we get this merged I'll probably fork it to make a LibreELEC specific version with the correct artwork.

2016-12-04 19:37 UTC, LS80 commented on resources/lib/builds.py
> +    BUILD_RE = (".*{release}.*-{arch}-(?:\d+\.\d+-|)[a-zA-Z]+-(\d+)"
Probably `dist` or `distribution` is a better name than `release`.

2016-12-04 19:37 UTC, LS80 commented on resources/lib/builds.py
> +        self.build_re = re.compile(self.BUILD_RE.format(release=openelec.OS_RELEASE['NAME'],arch=arch))
How about a `dist` function in the `openelec` module which just returns `OS_RELEASE['NAME']`. That would read better I think.

2016-12-04 19:37 UTC, LS80 commented on resources/lib/builds.py
> +        self.build_re = re.compile(self.BUILD_RE.format(release=openelec.OS_RELEASE['NAME'],arch=arch))
Missing space after the comma

2016-12-04 19:37 UTC, LS80 commented on resources/lib/builds.py
> +        BASE_URL = "http://releases.libreelec.tv"
Could be reduced to one line
```
BASE_URL = "http://releases.{dist}.tv".format(dist=openelec.dist().lower())
```

2016-12-04 19:37 UTC, LS80 commented on resources/lib/builds.py
> +            url = "http://milhouse.libreelec.tv/builds/"
Could be reduced to one line similar to the comment above.

2016-12-04 19:37 UTC, LS80 commented on resources/lib/builds.py
> +    if openelec.OS_RELEASE['NAME'] == "OpenELEC" or openelec.OS_RELEASE['NAME'] == "LibreELEC":
Could be 
```
if openelec.dist() in ("OpenELEC", "LibreELEC"):
```

2016-12-04 19:37 UTC, LS80 commented on resources/lib/openelec.py
> +if OS_RELEASE['NAME'] != "OpenELEC" and OS_RELEASE['NAME'] != "LibreELEC":
Could be
```
if openelec.dist() not in ("OpenELEC", "LibreELEC"):
```

2016-12-04 19:38 UTC, LS80 commented
I'll have a look at the problem with Official Releases.

2016-12-04 23:59 UTC, neox387 commented
It was just a quick dirty fix months ago :) & recently change to v18 forum post.

All tough LibreElec now has a build-in updater but I have not used it yet, I think it doesn't give a changelog not sure ..

2016-12-11 16:21 UTC, closed without merging